name: .NET CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore src/TicketsPlease.slnx
    - name: Restore tools
      run: dotnet tool restore
    - name: Verify Formatting
      run: dotnet format src/TicketsPlease.slnx --verify-no-changes
    - name: Build
      run: dotnet build src/TicketsPlease.slnx --no-restore --configuration Release
    - name: Test
      run: dotnet test src/TicketsPlease.slnx --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: thollander/actions-comment-pull-request@v3
      if: github.event_name == 'pull_request'
      with:
        file-path: ./code-coverage-results.md
