name: "Markdown Lint"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Lint Markdown
        uses: DavidAnson/github-actions-markdownlint@v1
        with:
          glob: '**/*.md'
          ignore: 'node_modules/**'

      - name: Check Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          check-modified-files-only: 'yes'
          base-branch: 'main'
          config-file: '.github/mlc_config.json'
